### ISSUE TITLE
Fix Broken Links - round 1

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#107]
There are 60+ broken links in the wiki. These need to be updated. Since they are spread over multiple repos, please create an issue for each repo and track them in the following list:

```[tasklist]
### Tasks
- [x] https://github.com/iotaledger/guild-devx/issues/108
- [x] https://github.com/iotaledger/guild-devx/issues/109
- [x] https://github.com/iotaledger/guild-devx/issues/110
- [x] https://github.com/iotaledger/guild-devx/issues/111
- [x] https://github.com/iotaledger/guild-devx/issues/112
- [x] https://github.com/iotaledger/guild-devx/issues/113
- [x] https://github.com/iotaledger/guild-devx/issues/114
```
