### ISSUE TITLE
Readup research produced wiki content for edu campaign

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/devx#115]
Read the wiki content research is producing right now for the education campaign and figure out:
- What kind of target audience probably is met with the content
- What kind of things are not really understandable?
- What should we produce from DevX side to make the content more accessible
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/119
- [ ] https://github.com/iotaledger/devx/issues/122
- [ ] https://github.com/iotaledger/devx/issues/164
- [ ] https://github.com/iotaledger/devx/issues/161
- [ ] https://github.com/iotaledger/devx/issues/163
- [ ] https://github.com/iotaledger/devx/issues/123
```
