### ISSUE TITLE
Move and delete docs from all external repos

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/devx#121]
As most of the Wiki content will be hosted in the wiki from no on, we should remove the docs from all repos which aren't needed anymore.
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/128
- [ ] https://github.com/iotaledger/devx/issues/129
- [ ] https://github.com/iotaledger/devx/issues/130
- [ ] https://github.com/iotaledger/devx/issues/131
- [ ] https://github.com/iotaledger/devx/issues/132
- [ ] https://github.com/iotaledger/devx/issues/133
- [ ] https://github.com/iotaledger/devx/issues/134
- [ ] https://github.com/iotaledger/devx/issues/135
- [ ] https://github.com/iotaledger/devx/issues/136
- [ ] https://github.com/iotaledger/devx/issues/137
- [ ] https://github.com/iotaledger/devx/issues/138
- [ ] https://github.com/iotaledger/devx/issues/139
- [ ] https://github.com/iotaledger/devx/issues/140
- [ ] https://github.com/iotaledger/devx/issues/141
- [ ] https://github.com/iotaledger/devx/issues/142
- [ ] https://github.com/iotaledger/devx/issues/143
- [ ] https://github.com/iotaledger/devx/issues/144
- [ ] https://github.com/iotaledger/devx/issues/145
- [ ] https://github.com/iotaledger/devx/issues/146
- [ ] https://github.com/iotaledger/devx/issues/147
- [ ] https://github.com/iotaledger/devx/issues/148
- [ ] https://github.com/iotaledger/devx/issues/150
- [ ] https://github.com/iotaledger/devx/issues/151
- [ ] https://github.com/iotaledger/devx/issues/152
- [ ] https://github.com/iotaledger/devx/issues/149
- [ ] https://github.com/iotaledger/devx/issues/153
- [ ] https://github.com/iotaledger/devx/issues/154
- [ ] https://github.com/iotaledger/devx/issues/155
- [ ] https://github.com/iotaledger/devx/issues/156
- [ ] https://github.com/iotaledger/devx/issues/157
- [ ] https://github.com/iotaledger/devx/issues/158
- [ ] https://github.com/iotaledger/devx/issues/159
- [ ] https://github.com/iotaledger/devx/issues/160
```
