### ISSUE TITLE
IOTA 2.0 docs

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#17]
## Goal

Successfully launch the IOTA 2.0 education campaign and part of this will include descriptions of IOTA 2.0 on the wiki
 
## Objective

Create the technical content and have DevX create introductory/ELI5 content around IOTA 2.0 on wiki

For existing generated contents:
- Create a PR. Depending on where in the wiki in which repo; 
- Assuming it's for GoShimmer, they need to add to [this folder](https://github.com/iotaledger/goshimmer/tree/develop/documentation/docs) and update [this file](https://github.com/iotaledger/goshimmer/blob/develop/documentation/sidebars.js) to include their new files 
  - We will be creating a new repo for this.
- Once it is merged it should get published at midnight

Items that need to confirm:
- What contents need an update to the wiki? Or just a protocol overview
- Check if the research team wants to update the 2.0 specification docs? We should commit to one section 
  **- We will be creating a new repository for this.**
- Put some more thought into how we handle versioning in the wiki (The idea is that Stardust changes eventually go into IOTA, to prepare it for the GoShimmer changes to be merged?)

Alternatives:  Share the contents/technical docs with Lucas and write a summary based on that 

## Tasks

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/guild-devx/issues/24
- [ ] https://github.com/iotaledger/guild-devx/issues/25
- [ ] https://github.com/iotaledger/guild-devx/issues/115
```
