### ISSUE TITLE
Build up IOTA 2.0 knowledge within the DevX team

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/devx#188]
The DevX team also needs to understand the IOTA 2.0 protocol in holder to help out others and create content around it. Please read the TIPs carefully and post any questions you have in following spreadsheet: https://docs.google.com/spreadsheets/d/18Q4_FopIAUKmo4DwTNVLo_-mHTJArEmEQmWNzmTNOl8/edit?usp=sharing

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/190
- [ ] https://github.com/iotaledger/devx/issues/191
- [ ] https://github.com/iotaledger/devx/issues/192
- [ ] https://github.com/iotaledger/devx/issues/193
```
