### ISSUE TITLE
Glossary - Update and add IOTA 2.0 terms

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#199]
Please review all current IOTA 2.0 specific definitions are still correct, and add new terms as well.

or example, https://github.com/iotaledger/iota-wiki/pull/1080#discussion_r1284744178.

## Doubt

@Dr-Electron , since the glossary is a JSON file, would it make sense to split it by network or topic? This way it'd be a bit more manageable perhaps. Off the top of my head I can think it makes sense to split it into Chrysalis, Stardust, IOTA 2.0, and common which would include terms that are not specific to networks
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/300
- [ ] https://github.com/iotaledger/devx/issues/301
- [ ] https://github.com/iotaledger/devx/issues/302
- [ ] https://github.com/iotaledger/devx/issues/303
- [ ] https://github.com/iotaledger/devx/issues/304
```
