### ISSUE TITLE
Mido Onboarding

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/devx#202]
This issue reflects the onboarding tasks for @trungtt1981.

```[tasklist]
### Tasks
- [x] Setup a private network using Hornet + Explorer + Chronicle
- [x] Setup an ISC network (our layer 2 SC solution) on top of a L1 network and deploy a solidity SC on it.
- [x] Write an application using the IOTA SDK (we have bindings for it in TypeScript, Python or Rust) which does L1 to L2 (and vice versa). For example something like an NFT marketplace which supports both layers.
- [x] Read the TIPs regarding the Chrysalis
- [x] Read the TIPs regarding Stardust
- [x] Read the [TIPs regarding IOTA 2.0](https://github.com/iotaledger/tips-draft)
```
