### ISSUE TITLE
2.0 - Add Batch 1 articles  to private wiki repo

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#215]
Please add the first batch of articles comms has prepared to the wiki's private fork and prepare a PR to the main wiki for the following articles:

```[tasklist]
### Tasks
- [x] Wiki: 5 principles (in theory and how we achieve them)
- [x] Wiki: Data flow; how all the components fit together
- [x] Wiki: Data structures (tx, branch ids, [multiverse reality], contained in blocks, the tangle, epoch committments, made sense off by markers
- [x] Wiki: Mana, accounts and tokenomics and staking
- [ ] Wiki: Consensus, commitee, approval weight, finality gadget
- [x] Wiki: Validators, their selection and rotation
```

**You should only add articles which have the _Locked_ column in the [comms spreadsheet](https://docs.google.com/spreadsheets/d/1DznMEEzvNAj_Z-9JPhhxTQ40NksqSMaY7q9n70uXLZo/edit#gid=388339278) set to Yes**
