### ISSUE TITLE
Learn - Create Diagrams and Add Images

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#219]
Based on the list from https://github.com/iotaledger/devx/issues/198 , please create or add the images or diagrams to the following sections in Learn:

```[tasklist]
### Tasks
- [ ] https://wiki.iota.org/learn/protocols/coordinator/ 
- [ ] https://wiki.iota.org/learn/protocols/chrysalis/introduction/
- [ ] https://wiki.iota.org/learn/protocols/chrysalis/introduction/.
- [ ] https://wiki.iota.org/learn/protocols/chrysalis/core-concepts/white-flag-consensus/ 
- [ ] https://wiki.iota.org/learn/protocols/chrysalis/core-concepts/switch-to-UTXO/
- [ ] https://wiki.iota.org/learn/protocols/chrysalis/core-concepts/EdDSA-support/
- [ ] https://wiki.iota.org/learn/protocols/chrysalis/core-concepts/binary-transaction-layout/ 
- [ ] https://wiki.iota.org/learn/protocols/stardust/introduction/
- [ ] https://wiki.iota.org/learn/protocols/stardust/core-concepts/multi-asset-ledger/
- [ ] https://wiki.iota.org/learn/protocols/stardust/core-concepts/output-unlock-conditions/
- [ ] https://wiki.iota.org/learn/protocols/stardust/core-concepts/output-features/
```
