### ISSUE TITLE
Bootstrap our EVM Ecosystem

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#229]
Epic to track the progress of all key results that aim to collobarate to improve the developer experience for ISC EVM.

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/239
- [ ] https://github.com/iotaledger/devx/issues/240
- [ ] https://github.com/iotaledger/devx/issues/242
- [ ] https://github.com/iotaledger/devx/issues/243
- [ ] https://github.com/iotaledger/iota-wiki/issues/1155
- [ ] https://github.com/iotaledger/devx/issues/298
- [ ] https://github.com/iotaledger/devx/issues/268
- [ ] https://github.com/iotaledger/iota-wiki/issues/1359
- [ ] https://github.com/iotaledger/devx/issues/314
- [ ] https://github.com/iotaledger/devx/issues/319
- [ ] https://github.com/iotaledger/devx/issues/318
- [ ] https://github.com/iotaledger/devx/issues/321
- [ ] https://github.com/iotaledger/devx/issues/244
- [ ] https://github.com/iotaledger/devx/issues/317
- [ ] https://github.com/iotaledger/iota-wiki/issues/1381
- [ ] https://github.com/iotaledger/iota-wiki/issues/1476
- [ ] https://github.com/iotaledger/devx/issues/344
```
