### ISSUE TITLE
Collaborate to the IOTA 2.0 Testnet launch

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#230]
Epic to group all the issues related to collaborating to the succesful launch of the IOTA 2.0 Testnet.

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/231
- [ ] https://github.com/iotaledger/devx/issues/232
- [ ] https://github.com/iotaledger/devx/issues/233
- [ ] https://github.com/iotaledger/devx/issues/234
- [ ] https://github.com/iotaledger/devx/issues/235
- [ ] https://github.com/iotaledger/devx/issues/236
- [ ] https://github.com/iotaledger/devx/issues/237
- [ ] https://github.com/iotaledger/devx/issues/238
- [ ] https://github.com/iotaledger/devx/issues/322
- [ ] https://github.com/iotaledger/devx/issues/323
- [ ] https://github.com/iotaledger/devx/issues/325
- [ ] https://github.com/iotaledger/devx/issues/351
- [ ] https://github.com/iotaledger/devx/issues/352

```

**Comment by lucas-tortora** [comment]
Let's put a pin in this for now.
