### ISSUE TITLE
Make 2.0 Content accessible to all user levels

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#232]
Based on https://github.com/iotaledger/devx/issues/231, please:

```[tasklist]
### Tasks
- [ ] Update the articles based on the review content
- [ ] Create higher level articles (if necessary)
- [ ] Add links to tips where appropriate
```
