### ISSUE TITLE
Structure iota-core docs following diataxis

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#233]
Please get the iota-core documentation up to the current standard:

```[tasklist]
### Tasks
- [ ] Organize docs with [diataxis](https://diataxis.fr/) 
- [ ] Ensure all the content follows the style guide
- [ ] Make any and all examples accesible by adding snippets of the relevant example code, and a short explanation with API references where relevant
```
