### ISSUE TITLE
Create getting started guides for sdk docs

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#236]
To ensure any developer can easily start building on IOTA 2.0, please create getting started guides Rust and all available bindings.
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/337
- [ ] https://github.com/iotaledger/devx/issues/339
- [ ] https://github.com/iotaledger/devx/issues/338
- [ ] https://github.com/iotaledger/devx/issues/340
```
