### ISSUE TITLE
Port the current Shimmer how tos to IOTA 2.0

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#237]
As we want to ensure the migration to IOTA 2.0 is as simple and seamless as possible, please port the current Stardust sdk how-to guides to IOTA 2.0:

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/249
- [ ] https://github.com/iotaledger/devx/issues/250
- [ ] https://github.com/iotaledger/devx/issues/251
- [ ] https://github.com/iotaledger/devx/issues/252
- [ ] https://github.com/iotaledger/devx/issues/253
- [ ] https://github.com/iotaledger/devx/issues/254
- [ ] https://github.com/iotaledger/devx/issues/255
- [ ] https://github.com/iotaledger/devx/issues/256
- [ ] https://github.com/iotaledger/devx/issues/257
- [ ] https://github.com/iotaledger/devx/issues/258
- [ ] https://github.com/iotaledger/devx/issues/345
```
