### ISSUE TITLE
Create static site to host archived docs

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#247]
When content gets deprecated,  it is no longer relevant to our target audience. However, as some devs may still be using deprecated software for some reason, we should make sure it's available but not cluttering our Wiki and search results. Please create a secondary wiki with deprecated content, for example, archive.wiki.iota.org. This wiki should be a fork of the current wiki where old docs go to die.  
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/280
- [ ] https://github.com/iotaledger/devx/issues/281
- [ ] https://github.com/iotaledger/devx/issues/282
- [ ] https://github.com/iotaledger/devx/issues/283
- [ ] https://github.com/iotaledger/devx/issues/248
```
