### ISSUE TITLE
Archive old, deprecated or no longer relevant docs

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#248]
Once the [archive](https://github.com/iotaledger/devx/issues/247) has been created, please move the following docs there:

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/259
- [ ] https://github.com/iotaledger/devx/issues/260
- [ ] https://github.com/iotaledger/devx/issues/261
- [ ] https://github.com/iotaledger/devx/issues/262
- [ ] https://github.com/iotaledger/devx/issues/263
- [ ] https://github.com/iotaledger/devx/issues/264
- [ ] https://github.com/iotaledger/devx/issues/265
```

**Comment by lucas-tortora** [comment]
We've opted against creating an archive. Instead, deprecated docs will be marked as such and blocked from crawlers and Algolia.  After a grace period of ~3 months, we should delete them.
