### ISSUE TITLE
IOTA Sandbox

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#286]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/iota-sandbox/issues/5
- [ ] https://github.com/iotaledger/iota-sandbox/issues/9
- [ ] https://github.com/iotaledger/iota-sandbox/issues/6
- [ ] https://github.com/iotaledger/iota-sandbox/issues/7
- [ ] https://github.com/iotaledger/iota-sandbox/issues/8
- [ ] https://github.com/iotaledger/iota-sandbox/issues/11
- [ ] https://github.com/iotaledger/iota-wiki/issues/1343
- [ ] https://github.com/iotaledger/iota-sandbox/issues/14
- [ ] https://github.com/iotaledger/iota-sandbox/issues/15
```
