### ISSUE TITLE
Port RustyBot Tutorials for IOTA EVM

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#317]
In order to enable a good developer experience, we need to provide resources so our users can easily use IOTA EVM. Please port the following tutorials:

```[tasklist]
### Tasks
- [x] Connect to Shimmer EVM
- [x] https://docs.rustyrobot.io/how-to/shimmer/buy-shimmer-native-token-usdsmr
- [x] https://docs.rustyrobot.io/how-to/shimmer/create-an-address-on-shimmerevm
- [x] https://docs.rustyrobot.io/how-to/shimmer/transfer-usdsmr-to-evm
```
