### ISSUE TITLE
Prepare the Wiki for 3.0 (software-side)

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#355]
```[tasklist]
### Tasks
- [ ] Implement versioning using Docusaurus
- [ ] Update the Wiki to 3.0 style
- [ ] Update and simplify the wiki's component architecture
- [ ] Automate documentation generation
```
