### ISSUE TITLE
[Epic(docs)] - Improve EVM DevEX

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#366]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/367
- [ ] https://github.com/iotaledger/devx/issues/368
- [ ] https://github.com/iotaledger/devx/issues/369
- [ ] https://github.com/iotaledger/devx/issues/370
- [ ] https://github.com/iotaledger/devx/issues/393
- [ ] https://github.com/iotaledger/devx/issues/396
- [ ] https://github.com/iotaledger/devx/issues/398
- [ ] https://github.com/iotaledger/devx/issues/439
- [ ] https://github.com/iotaledger/devx/issues/440
```
