### ISSUE TITLE
ISC Eco Launch Updates

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#402]
```[tasklist]
### Tasks
- [x] Give IOTA EVM more protagonism in the home page, announcement bar and/or navbar.
- [x] Add Blast API in IOTA EVM network info admonition
- [x] Oracles page needs to be about IOTA EVM
- [ ] Add tabs for code snippets in oracles (devEx after the new code example is provided by Mido)
- [x] Move Pyth on top of Supra (devEx)
```
