### ISSUE TITLE
ISC ECO Immediate Updates

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#403]
```[tasklist]
### Tasks
- [x] Remove Staking PAge
- [ ] Remove links to https://evm-faucet.testnet.shimmer.network
- [ ] Ask devOps to take https://evm-faucet.testnet.shimmer.network/ down
```
