### ISSUE TITLE
Merge content from the move-book into the monorepo

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#406]
Please go through the following content and add anything you find relevant to the SUI Docs in the mono repo. Please search for references on these topics throughout the entire documentation, and add tags in the header YML to reflect the diataxis type/s, the main addressed topics, and functions.

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/408
- [ ] https://github.com/iotaledger/devx/issues/409
- [ ] https://github.com/iotaledger/devx/issues/410
- [ ] https://github.com/iotaledger/devx/issues/411
- [ ] https://github.com/iotaledger/devx/issues/412
- [ ] https://github.com/iotaledger/devx/issues/413
- [ ] https://github.com/iotaledger/devx/issues/414
- [ ] https://github.com/iotaledger/devx/issues/415
```
