### ISSUE TITLE
Concepts

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#409]
Please go through the following content and add anything you find relevant to the SUI Docs in the mono repo. Please search for references on these topics throughout the entire documentation, and add tags in the header YML to reflect the diataxis type/s, the main addressed topics, and functions.

```[tasklist]
### Tasks
- [x] https://move-book.com/concepts/packages.html
- [x] https://move-book.com/concepts/manifest.html
- [x] https://move-book.com/concepts/address.html
- [x] https://move-book.com/concepts/what-is-an-account.html
- [x] https://move-book.com/concepts/what-is-a-transaction.html
```

Please feel free to edit the docs while merging, but don't be too concerned about style as this will be addressed once the content has been unified.
