### ISSUE TITLE
Replace any lingering outdated terms

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#425]
Please review all the documentation and ensure it's properly branded with IOTA. This includes the following:

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/469
- [ ] https://github.com/iotaledger/devx/issues/468
- [x] Replace Sui with IOTA
```
