### ISSUE TITLE
Review and create PRs for the created issues in ISC

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#426]
As part of the EVM launch, we created a list of issues in the WASP repository we should address to improve the overall developer experience:

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/wasp/issues/3411
- [ ] https://github.com/iotaledger/wasp/issues/3343
- [ ] https://github.com/iotaledger/wasp/issues/3330
- [ ] https://github.com/iotaledger/wasp/issues/3324
- [ ] https://github.com/iotaledger/wasp/issues/3323
- [ ] https://github.com/iotaledger/wasp/issues/3322
- [ ] https://github.com/iotaledger/wasp/issues/3267
- [ ] https://github.com/iotaledger/wasp/issues/3265
- [ ] https://github.com/iotaledger/wasp/issues/3422
- [ ] https://github.com/iotaledger/wasp/issues/3325
```
