### ISSUE TITLE
Remove unsupported tools

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#437]
Please update the docs to ensure that all support for the following features has been removed:

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/466
- [ ] https://github.com/iotaledger/devx/issues/465
- [ ] https://github.com/iotaledger/devx/issues/467
- [x] swaps (tenian swaps con USDT creo que lo quitamos tb)
- [x] fiat on ramp
- [x] QR Redo
```
