### ISSUE TITLE
[Epic (docs)]- Review all how tos for move compatibility

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#440]
With the changes in L1, we should ensure all the how-to guides in the ISC documentation still hold. For this purpose, please go through the following guides, run and update them if necessary:

```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/devx/issues/441
- [ ] https://github.com/iotaledger/devx/issues/442
- [ ] https://github.com/iotaledger/devx/issues/443
- [ ] https://github.com/iotaledger/devx/issues/444
- [ ] https://github.com/iotaledger/devx/issues/445
```
