### ISSUE TITLE
[Task (docs)] - Test Basics Section

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#441]
With the changes in L1, we should ensure all the how-to guides in the ISC documentation still hold. For this purpose, please go through the following guides, run and update them if necessary:

```[tasklist]
### Tasks
- [x] Basics - Allowance - Allow
- [x] Basics - Allowance - Get Allowance
- [x] Basics - Allowance - Take Allowance
- [x] Basics - Get Balance
- [x] Basics - Send Assets to L1
```

```[tasklist]
### Tasks
```
