### ISSUE TITLE
[Task (docs)] - Test NFT Section

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#442]
With the changes in L1, we should ensure all the how-to guides in the ISC documentation still hold. For this purpose, please go through the following guides, run and update them if necessary:

```[tasklist]
### Tasks
- [x] NFT - Get L2 NFTs
- [x] NFT - Get NFT Metadata
- [x] NFT - Mint NFT
- [x] NFT - Use as ERC-721
```

```[tasklist]
### Tasks
```
