### ISSUE TITLE
[Task (docs)] - Test Token Section

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#443]
With the changes in L1, we should ensure all the how-to guides in the ISC documentation still hold. For this purpose, please go through the following guides, run and update them if necessary:

```[tasklist]
### Tasks
- [x] Token - Create Foundry
- [x] Token - Create Native Token
- [x] Token - ERC 20 Native Token
- [x] Token - Mint Token
- [x] Token - Register Token
- [x] Token - Send Across Chains
```
