### ISSUE TITLE
[Task (docs)] - Test EVM Basics

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger/devx#445]
With the changes in L1, we should ensure all the how-to guides in the ISC documentation still hold. For this purpose, please go through the following guides, run and update them if necessary:

```[tasklist]
### Tasks
- [x] Send NFTs Accross Chains
- [x] Send Funds From L1 to L2
- [x] Send ERC 20 Across Chains
- [x] ERC 721
- [x] ERC 20
- [x] Create a Basic Contract
```
