### ISSUE TITLE
Wiki tutorial section revamp

### ISSUE THREAD

**Issue by annie101101046** [iotaledger/devx#46]
**Goal:** Our wiki is designed to be a comprehensive platform that supports the entire developer learning and onboarding journey, from the initial discovery phase to playing, building, and ultimately shipping the product

**Objective:** Each stage should have a specific user story for both the onboarding and learning experience. 

For instance, in the "Discover" section, a story might read, "I am a developer who wants to build on the Shimmer network. I need a one-stop section where I can quickly find where to start and access all the necessary documentation." 

**Our approach:** We will determine the story and current pain points for each section, and ensure that we include all the necessary ingredients to provide an exceptional developer experience.

### TODO
- [x] Identify "Discover" stage content lists for both Shimmer & ShimmerEVM 
- [x] Identify "Play" stage content lists for both Shimmer & ShimmerEVM 
- [x] Identify "Build" stage content lists for both Shimmer & ShimmerEVM 
- [x] Identify "Ship" content lists for both Shimmer and ShimmerEVM
- [ ] Create "Discover" stage contents
- [ ] Create "Play" stage contents
- [ ] Create  "Build" stage contents
- [ ] Create "Ship" stage contents
- [ ] Discover, Play, Build, Ship stage content review 
- [ ] Wiki new tutorial section restructure and UX re-design
- [ ] Wiki new tutorial section new structure implementation
- [ ] Wiki new tutorial section community launch
