### ISSUE TITLE
Create a summary report / analysis of L1 library testing

### ISSUE THREAD

**Issue by annie101101046** [iotaledger/devx#9]
## **Description**

Testing L1 libraries and providing a summary report

## **TODO**
 
- [x] [iota.rs/iota.js](http://iota.rs/iota.js) testing
- [x] [wallet.rs](http://wallet.rs/) testing
- [x] hornet testing 
- [x] cli-wallet testing
- [x] Generate a library review note
- [x] Generate a library review summary
