### ISSUE TITLE
Office Hours

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/devx#90]
```[tasklist]
### Tasks
- [ ] https://github.com/iotaledger/guild-devx/issues/92
- [ ] https://github.com/iotaledger/guild-devx/issues/91
- [ ] https://github.com/iotaledger/guild-devx/issues/102
- [ ] https://github.com/iotaledger/guild-devx/issues/116
- [ ] https://github.com/iotaledger/devx/issues/118
- [ ] https://github.com/iotaledger/devx/issues/127
```
